import "./globals/global.css";
import Menu from "./globals/Menu";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Menu />
        <div className="max-w-6xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
